name: Pinboard
version: 1.0
description: >
  Periodically polls your Pinboard account
  and creates link entries
url: https://github.com/edalzell
developer: Erin Dalzell
developer_url: https://github.com/edalzell
