fields:
  token:
    type: text
    display: Pinboard Token
    instructions: Get it [here](https://pinboard.in/settings/password)
  pinboard_tag:
    type: suggest
    mode: pinboard.tags
    max_items: 1
    instructions: Grab bookmarks with this tag
  category_term:
    type: suggest
    max_items: 1
    mode: pinboard.all_terms
    instructions: This is the category all bookmarks will be assigned to
  tag_taxonomy:
    type: suggest
    mode: pinboard.taxonomies
    max_items: 1
    instructions: This is the taxonomy the bookmark tags will be added to
  category_taxonomy:
    type: suggest
    mode: pinboard.taxonomies
    max_items: 1
    instructions: Taxonomy to save the below Pinboard tags into
  category_tags:
    type: suggest
    mode: pinboard.tags
    instructions: The bookmark tags will be saved into the above taxonomy
  collection:
    type: collections
    max_items: 1
    instructions: Collection to add the bookmarks too
  author:
    type: users
    max_items: 1