fields:
  token:
    type: text
  pinboard_tag:
    type: suggest
    mode: pinboard.tags
    max_items: 1
  category_term:
    type: suggest
    max_items: 1
    mode: pinboard.all_terms
  tag_taxonomy:
    type: suggest
    mode: pinboard.taxonomies
    max_items: 1
  category_taxonomy:
    type: suggest
    mode: pinboard.taxonomies
    max_items: 1
  category_tags:
    type: suggest
    mode: pinboard.tags
  collection:
    type: collections
    max_items: 1
  author:
    type: users
    max_items: 1